name: Compile & Check

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch: # Manual trigger added
  workflow_call: # Allow other Actions to call this workflow

jobs:
  Compile-and-Check:
    runs-on: windows-latest
    steps:
    - name: Checkout Sources
      uses: actions/checkout@v6

    - name: Compile and Syntaxcheck winutil.ps1
      shell: pwsh
      run: |
        Set-ExecutionPolicy Bypass -Scope Process -Force; ./Compile.ps1
      continue-on-error: false # Directly fail the job on error, removing the need for a separate check
